# Generated by Django 4.0.1 on 2022-03-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['pages']},
        ),
    ]
